import Head from "next/head";

const CalendarGuidePage = () => {
  return (
    <>
      <Head>
        <title>Meetbot | Google Calendar Integration Guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-lg m-auto px-6 py-8 bg-yellow-200 rounded-sm shadow-md">
        <h1 className="text-center">Integrate with Google Calendar</h1>
        <p>
          Meetbot needs to be able to read and write data to your Google
          Calendar in order for it to sync your meetings properly.
        </p>
        <p>
          You can allow this on a per-calendar basis by going into the Google
          Calendar's settings and adding&nbsp;
          <a href="mailto:calendar@meetbot-hq.iam.gserviceaccount.com">
            calendar@meetbot-hq.iam.gserviceaccount.com
          </a>
          &nbsp;as a <b>Make changes to events</b> user.
        </p>
        <p>
          You'll also need your Google Calendar's ID, which can be found under
          the <b>Integrate calendar</b> heading in your calendar's settings.
        </p>

        <p>Resources</p>
        <ul>
          <li>
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://support.google.com/calendar/answer/37082"
            >
              Share your calendar with someone
            </a>
          </li>
          <li>
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://docs.simplecalendar.io/find-google-calendar-id/"
            >
              Finding Your Google Calendar ID
            </a>
          </li>
        </ul>
      </div>
    </>
  );
};

export default CalendarGuidePage;
