import Head from "next/head";
import { OnboardingChecklist } from "components/onboarding/OnboardingChecklist";

const OnboardPage = () => {
  return (
    <>
      <Head>
        <title>VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center">Welcome to Hack for LA! 🎉</h1>
      <p className="text-center">Here's your onboarding checklist:</p>
      <OnboardingChecklist />
    </>
  );
};

OnboardPage.auth = {};

export default OnboardPage;
