version: "3.1"

services:
  app:
    image: tmshkr/meetbot:${ENVIRONMENT}
    command: npm run start:test
    env_file:
      - .env
    restart: always
    depends_on:
      - nginx
      - db
      - mongo
    environment:
      DATABASE_URL: mysql://root:example@db:3306/meetbot
      MONGO_URI: mongodb://root:example@mongo:27017/meetbot?authSource=admin
      NEXTAUTH_URL: https://localhost
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  nginx_secrets:
