version: "3"

services:
  postgres:
    image: "postgres:latest"
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres/vrms
    depends_on:
      - postgres
  slackbot:
    build:
      context: .
      dockerfile: ./apps/slackbot/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres/vrms
    depends_on:
      - postgres
