version: "3"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    command: npm run dev
    env_file:
      - .env
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres/vrms
    depends_on:
      - postgres
      - nginx

volumes:
  nginx_secrets:
  pgdata:
