version: "3"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  slackbot:
    image: tmshkr/vrms:latest
    command: npm run start:slackbot
    env_file:
      - .env
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres/vrms
    depends_on:
      - postgres
  web:
    image: tmshkr/vrms:latest
    command: npm run start:web
    env_file:
      - .env
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres/vrms
    depends_on:
      - postgres
      - slackbot

volumes:
  nginx_secrets:
  pgdata:
