version: "3"

services:
  app:
    image: tmshkr/vrms:latest
    command: npm run start
    env_file:
      - .env
    restart: always
    depends_on:
      - nginx
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:
