import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import prisma from "common/prisma";
import dayjs from "common/dayjs";
import { getNextOccurrence } from "common/meetings";
import { generateEventLink } from "common/google";

const Projects: NextPage = (props: any) => {
  const { project } = props;

  return (
    <>
      <Head>
        <title>Projects | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{project.name}</h1>
      <h2>👥 Team Members</h2>
      <ul>
        {project.team_members.map(({ member, position, role }) => {
          return (
            <li key={member.id}>
              <Link href={`/people/${member.id}`}>{member.real_name}</Link>
            </li>
          );
        })}
      </ul>
      <h3>📅 Upcoming Meetings</h3>
      <ul>
        {project.meetings.map((meeting) => {
          return (
            <li key={meeting.id} suppressHydrationWarning>
              <Link href={`/meetings/${meeting.id}`}>{meeting.title}</Link>
              <br />
              {dayjs(meeting.nextMeeting).format("MMM D, h:mm a")}
              <br />
              <a
                href={meeting.gcalEventLink}
                target="_blank"
                rel="noopener noreferrer"
                suppressHydrationWarning
              >
                Add to Calendar
              </a>
            </li>
          );
        })}
      </ul>
    </>
  );
};

export default Projects;

export async function getServerSideProps(context) {
  const id = Number(context.params.id);

  if (!id) {
    return {
      redirect: {
        destination: "/projects",
        permanent: false,
      },
    };
  }

  const project = await prisma.project.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      meetings: {
        include: {
          exceptions: {
            where: { status: "CONFIRMED" },
            orderBy: { start_time: "asc" },
          },
        },
      },
      team_members: {
        select: {
          role: true,
          position: true,
          member: { select: { id: true, real_name: true } },
        },
      },
    },
  });

  if (!project) {
    return {
      notFound: true,
    };
  }

  for (const meeting of project.meetings) {
    const nextMeeting = getNextOccurrence(meeting);

    (meeting as any).nextMeeting = nextMeeting;
    (meeting as any).gcalEventLink = generateEventLink(
      meeting.gcal_event_id,
      nextMeeting
    );
  }

  return {
    props: { project },
  };
}
