import { getToken } from "next-auth/jwt";
import Head from "next/head";
import prisma from "common/prisma";
import { getNextOccurrence } from "common/meetings";
import dayjs from "common/dayjs";

const MeetingCheckinPage = (props: any) => {
  const { meeting, message } = props;
  return (
    <>
      <Head>
        <title>Meeting | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{meeting.title}</h1>
      <p>{message}</p>
    </>
  );
};

export default MeetingCheckinPage;

export async function getServerSideProps(context) {
  const { req, res, params } = context;
  const id = Number(params.id);

  if (!id) {
    return {
      redirect: {
        destination: "/meetings",
        permanent: false,
      },
    };
  }

  const nextToken: any = await getToken({ req });
  if (!nextToken) {
    return {
      redirect: {
        destination: `/api/auth/signin?callbackUrl=${req.url}`,
        permanent: false,
      },
    };
  }

  try {
    const { provider, provider_account_id } = nextToken;
    var { user } = await prisma.account.findUniqueOrThrow({
      where: {
        provider_provider_account_id: {
          provider,
          provider_account_id,
        },
      },
      select: {
        user: {
          select: {
            id: true,
            slack_id: true,
          },
        },
      },
    });
  } catch (err) {
    return {
      redirect: {
        destination: `/onboard`,
        permanent: false,
      },
    };
  }

  const meeting = await prisma.meeting.findUnique({
    where: { id },
    include: {
      exceptions: {
        orderBy: { start_time: "asc" },
      },
    },
  });

  if (!meeting) {
    return {
      redirect: {
        destination: `/meetings`,
        permanent: false,
      },
    };
  }

  // 30 minute checkin window
  const checkinWindowStart = dayjs().subtract(15, "minute");
  const checkinWindowEnd = dayjs().add(15, "minute");

  const { startTime: meeting_time } = getNextOccurrence(
    meeting,
    checkinWindowStart.toDate()
  );

  if (!meeting_time) {
    return {
      props: {
        meeting: { title: meeting.title },
        message: "It looks like there are no more meetings scheduled",
      },
    };
  }

  if (
    !checkinWindowStart.isSameOrBefore(meeting_time) ||
    !checkinWindowEnd.isSameOrAfter(meeting_time)
  ) {
    return {
      props: {
        meeting: { title: meeting.title },
        message: "It looks like you're outside the checkin window",
      },
    };
  }

  let message;
  try {
    await prisma.meetingCheckin.create({
      data: {
        meeting_id: meeting.id,
        user_id: user.id,
        meeting_time,
      },
    });
    message = "Thanks for checking in!";
  } catch (err: any) {
    if (err.code === "P2002") {
      message = "It looks like you've already checked in to this meeting";
    } else {
      console.error(err);
      message = "There was a problem checking you in";
    }
  }

  return {
    props: {
      meeting: { title: meeting.title },
      message,
    },
  };
}
