name: Build and Deploy Docker Image
on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tmshkr/vrms:${{ steps.branch-name.outputs.current_branch }} .
      - run: docker push tmshkr/vrms:${{ steps.branch-name.outputs.current_branch }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Set server_name
        run: node nginx/server_name.js ${{ steps.branch-name.outputs.current_branch }}
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: vrms
          environment_name: vrms-${{ steps.branch-name.outputs.current_branch }}
          version_label: ${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: us-west-1
          deployment_package: deploy.zip
