name: Build and Deploy Docker Image
on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tmshkr/meetbot:${{ steps.branch-name.outputs.current_branch }} .
      - run: docker push tmshkr/meetbot:${{ steps.branch-name.outputs.current_branch }}
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    steps:
      - name: Set server_name
        run: node nginx/server_name.js "${{ secrets.SERVER_NAMES }}"
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: meetbot
          environment_name: meetbot-staging
          version_label: staging-${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: us-west-1
          deployment_package: deploy.zip
          wait_for_environment_recovery: 60
    deploy-main:
    runs-on: ubuntu-latest
    needs: build
    environment: main
    steps:
      - name: Set server_name
        run: node nginx/server_name.js "${{ secrets.SERVER_NAMES }}"
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: meetbot
          environment_name: meetbot-main
          version_label: main-${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: us-west-1
          deployment_package: deploy.zip
          wait_for_environment_recovery: 60
